services:
  - type: web
    name: sih-land-records
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils libgl1-mesa-glx libglib2.0-0 libjpeg-dev zlib1g-dev libpng-dev libfreetype6-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
